### ISSUE TITLE
Auth TypeError: this.client.prepare is not a function

### ISSUE THREAD

**Issue by xiemax100** [Dhravya/cloudflare-saas-stack#56]
Thanks for reading my issue. I have tried my best and could not find the root cause.

I just fork this repo template and before I add my own login page, user login through Github works.

But when I add my custom login page and other configurations (authjs, drizzle etc.) are all the same with this repo:
![image](https://github.com/user-attachments/assets/3e60d6c5-4fb3-4568-938b-1eec76434c73)

## I got errors below

> It seems due to the drizzle orm, because when I enable next-auth debug, the Oauth 2 flow is normal.

```
 GET /login 200 in 702ms
 POST /login 303 in 113ms
[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror
[auth][cause]: TypeError: this.client.prepare is not a function
    at SQLiteD1Session.prepareQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/d1/session.js:29:30)
    at SQLiteD1Session.prepareOneTimeQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/session.js:76:17)
    at SQLiteSelectBase._prepare (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/query-builders/select.js:586:88)
    at SQLiteSelectBase.get (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/query-builders/select.js:605:17)
    at getUserByAccount (webpack-internal:///(rsc)/./node_modules/@auth/drizzle-adapter/lib/sqlite.js:169:18)
    at acc.<computed> (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/init.js:174:30)
    at Module.callback (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/actions/callback/index.js:68:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/index.js:43:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:130:34)
[auth][details]: {}
[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror
[auth][cause]: TypeError: this.client.prepare is not a function
    at SQLiteD1Session.prepareQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/d1/session.js:29:30)
    at SQLiteD1Session.prepareOneTimeQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/session.js:76:17)
    at SQLiteSelectBase._prepare (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/query-builders/select.js:586:88)
    at SQLiteSelectBase.get (webpack-internal:///(rsc)/./node_modules/drizzle-orm/sqlite-core/query-builders/select.js:605:17)
    at getUserByAccount (webpack-internal:///(rsc)/./node_modules/@auth/drizzle-adapter/lib/sqlite.js:169:18)
    at acc.<computed> (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/init.js:174:30)
    at Module.callback (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/actions/callback/index.js:68:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/index.js:43:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:130:34)
[auth][details]: {}
 ⨯ Error [TypeError]: immutable
    at _Headers.delete (file://D:\Projects\Stay\StayStack\node_modules\next\dist\compiled\edge-runtime\index.js:1:657096)
    at <unknown> (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\web\sandbox\sandbox.js:117:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runWithTaggedErrors (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\web\sandbox\sandbox.js:107:9)
    at async DevServer.runEdgeFunction (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\next-server.js:1201:24)
    at async NextNodeServer.handleCatchallRenderRequest (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\next-server.js:248:37) 
    at async DevServer.handleRequestImpl (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\base-server.js:816:17)
    at async (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\dev\next-dev-server.js:339:20)
    at async Span.traceAsyncFn (file://D:\Projects\Stay\StayStack\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (file://D:\Projects\Stay\StayStack\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
 ✓ Compiled /_error in 319ms (562 modules)
 GET /api/auth/callback/github?code=d0d0055c02f21c7a0d69 500 in 2203ms
```

## Login page code:
```
'use client'

import Image from 'next/image'
import Link from 'next/link'
import { Github, ArrowLeft } from 'lucide-react'
import LoginForm from '@/components/features/LoginForm'
import { useRouter } from 'next/navigation'
import { githubSignIn } from '../actions/auth'

export const runtime = "edge"

export default function LoginPage() {
  const router = useRouter()

  return (
    <div className="fixed inset-0 z-50">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={() => router.back()}
      />

      {/* Back Button */}
      <Link 
        href="/"
        className="absolute top-4 left-4 flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors z-10"
      >
        <ArrowLeft className="w-4 h-4" />
        Back
      </Link>

      {/* Login Modal */}
      <div className="absolute inset-0 overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="min-h-full flex items-center justify-center p-4">
          <div className="relative w-full max-w-md space-y-8">
            {/* Panda Icon */}
            <div className="flex justify-center">
              <div className="w-16 h-16 bg-white/10 rounded-full flex items-center justify-center">
                <Image
                  src="/panda-icon.svg"
                  alt="Panda Logo"
                  width={40}
                  height={40}
                  className="text-white"
                />
              </div>
            </div>
            
            {/* Welcome Text */}
            <div className="text-center">
              <h1 className="text-2xl font-bold text-white">Welcome back</h1>
              <p className="mt-2 text-sm text-gray-400">
                Enter your email to log into your account
              </p>
            </div>

            {/* Login Form */}
            <LoginForm />

            {/* Divider */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-white/10"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-black text-gray-400">OR CONTINUE WITH</span>
              </div>
            </div>

            {/* Social Login */}
            <form action={githubSignIn}>
              <button
                type="submit"
                className="w-full flex items-center justify-center gap-2 px-4 py-2 border border-white/10 rounded-lg hover:bg-white/5 transition-colors"
              >
                <Github className="w-5 h-5" />
                <span>Github</span>
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

```

## Login action code:
```
"use server"

import { signIn, signOut } from "@/server/auth"

export async function githubSignIn() {
  try {
    await signIn("github", {
      callbackUrl: "/",
      redirect: true
    })
  } catch (error) {
    if ((error as any)?.digest?.includes('NEXT_REDIRECT')) {
      throw error;
    }
    console.error("GitHub sign in error:", error)
    throw error
  }
}

export async function userSignOut() {
  try {
    await signOut({
      redirect: true
    })
  } catch (error) {
    console.error("Sign out error:", error)
    throw error
  }
}
```

**Comment by brunowego** [comment]
Have you found a solution for this?

**Comment by Dhravya** [comment]
Hi! This issue does not seem related to the cloudflare stack. I'm closing this for now, but feel free to re-open it if needed.
